### PR TITLE
UPDATED: dependencies in package.json

### PR DESCRIPTION
**Pull request by agantelin**
### Updated:
- @kyvg/vue3-notification from 2 to latest 3 version (3.1.4)
- other dependencies (@nuxt/module-builder, eslint, prettier)
- lock file (yarn.lock) regenerated from scratch

### CODE REVIEW

**Comment by windx-foobar** [comment]
Hi! Thank u for PR.
Please tell me, did you check the functionality of the module after updating the package from @kyvg?
Still, the major version has been updated...

**Comment by agantelin** [comment]
Yes I tested the base functionality & execution of script commands from package.json. I didn't notice any errors.
Also I'm going to do a couple of PRs with fixes after merging this one.
What do you think about making the release v2.0-beta1? So, we could test it in projects.

**Comment by agantelin** [comment]
Also consider migrating Yarn to the latest version 4.1. Since version 1 is outdated and seems to be causing problems.

**Comment by windx-foobar** [comment]
> Also consider migrating Yarn to the latest version 4.1. Since version 1 is outdated and seems to be causing problems.

Ofc, in the next release I want to switch to pnpm.

> What do you think about making the release v2.0-beta1? So, we could test it in projects.

Great! Lets do it:)

**Pull request merged**
